# Generated by Django 4.0.4 on 2022-05-20 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Indisponível', 'Indisponível'), ('Disponível', 'Disponível')], default='Disponível', max_length=100),
        ),
    ]
